//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int id { get; set; }
        public string idCart { get; set; }
        public string password { get; set; }
        public string fullname { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> birth { get; set; }
        public string gender { get; set; }
        public string address { get; set; }
        public string sdt { get; set; }
    }
}
