//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int id { get; set; }
        public string idCart { get; set; }
        public string image { get; set; }
        public string nameProduct { get; set; }
        public Nullable<int> quantity { get; set; }
        public string size { get; set; }
        public string color { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
    }
}
